CREATE DATABASE EXAMEN2

USE EXAMEN2

CREATE TABLE CAJEROS
(
CodigoC INT IDENTITY(1,1),
NomApels NVARCHAR(255) NOT NULL,
CONSTRAINT PK_CodigoC PRIMARY KEY (CodigoC)
)

INSERT INTO CAJEROS VALUES ('Maryeri Morera Pereira')
INSERT INTO CAJEROS VALUES ('Victor Morera Pereira')

SELECT * FROM CAJEROS

CREATE TABLE PRODUCTOS
(
CodigoP INT IDENTITY(1,1),
Nombre NVARCHAR(100) NOT NULL,
Precio FLOAT DEFAULT 0,
CONSTRAINT PK_CodigoP PRIMARY KEY (CodigoP)
)

INSERT INTO PRODUCTOS VALUES ('Arroz', '2500')
INSERT INTO PRODUCTOS VALUES ('Leche', '1100')
INSERT INTO PRODUCTOS VALUES ('Cereal', '2900')

UPDATE PRODUCTOS SET Nombre='Frijoles' WHERE Nombre='Arroz'
UPDATE PRODUCTOS SET Precio='3600' WHERE Precio='1100'
SELECT * FROM PRODUCTOS

CREATE TABLE MAQUINAS
(
CodigoM INT IDENTITY(1,1),
Piso INT,
CONSTRAINT PK_CodigoM PRIMARY KEY (CodigoM)
)

INSERT INTO MAQUINAS VALUES ('1')
INSERT INTO MAQUINAS VALUES ('2')

SELECT * FROM MAQUINAS

CREATE TABLE VENTA
(
Codigo_Venta INT IDENTITY (1,1),
Fecha DATETIME NULL,
Cajero INT,
Maquina INT,
Producto INT,
CONSTRAINT PK_CodigoVenta PRIMARY KEY (Codigo_Venta),
CONSTRAINT FK_Cajero FOREIGN KEY (Cajero) REFERENCES CAJEROS(Codigoc),
CONSTRAINT FK_Maquina FOREIGN KEY (Maquina) REFERENCES MAQUINAS(CodigoM),
CONSTRAINT FK_Producto FOREIGN KEY (Producto) REFERENCES PRODUCTOS(CodigoP)
)

SELECT c.NomApels, p.Nombre, p.Precio, m.Piso FROM CAJEROS c, PRODUCTOS p INNER JOIN MAQUINAS m ON p.CodigoP = m.CodigoM

SELECT * FROM VENTA

